---
# golangci-lint configuration file made by @ccoVeille
# Source: https://github.com/ccoVeille/golangci-lint-config-examples/
# Author: @ccoVeille
# License: MIT
# Variant: 01-defaults
# Version: v2.0.0
#
version: "2"

linters:
  # some linters are enabled by default
  # https://golangci-lint.run/usage/linters/
  #
  enable:
    # Vet examines Go source code and reports suspicious constructs.
    - govet

    # Detects when assignments to existing variables are not used.
    - ineffassign

    # It's a set of rules from staticcheck. See https://staticcheck.io/
    - staticcheck

    # Checks Go code for unused constants, variables, functions and types.
    - unused
 
  disable:
    # TODO: enable errcheck and resolve all errors
    # Errcheck is a program for checking for unchecked errors in Go code.
    - errcheck

    - revive

  exclusions:
    rules:
      - linters: staticcheck
        # SA1019: Using a deprecated function, variable, constant or field
        text: "SA1019:"