# This is the configuration for golangci-lint.
# See https://golangci-lint.run/usage/configuration/ for details.

version: "2"

linters:
  default: none
  enable:
    - dupword
    - embeddedstructfieldcheck
    - gocritic
    - godoclint
    - godot
    - gosec
    - govet
    - ineffassign
    - misspell
    - modernize
    - musttag
    - nolintlint
    - recvcheck
    - revive
    - sloglint
    - staticcheck
    - testpackage
    - thelper
    - thelper
    - unconvert
    - unparam
    - unused
    - wastedassign

  exclusions:
    warn-unused: true
    rules:
      - path: '(.+)_test\.go'
        linters:
          - godoclint
          - godot
      - linters:
          - testpackage
        text: 'package should be `rule_test` instead of `rule`'
      - linters:
          - testpackage
        text: 'package should be `lint_test` instead of `lint`'
      - linters:
          - testpackage
        text: 'package should be `cli_test` instead of `cli`'
      - linters:
          - gosec
        path: rule/context_keys_type.go
      - linters:
          - gosec
        path: rule/errorf.go
      - linters:
          - gosec
        path: rule/modifies_value_receiver.go
      - linters:
          - gosec
        path: rule/range_val_address.go
      - linters:
          - gosec
        path: rule/string_of_int.go
      - linters:
          - gosec
        path: rule/time_naming.go
      - linters:
          - gosec
        path: rule/unexported_return.go
      - linters:
          - gosec
        path: rule/unhandled_error.go
      - linters:
          - gosec
        path: rule/var_declarations.go

  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - hugeParam
        - rangeValCopy
    godoclint:
      default: all
      options:
        max-len:
          length: 120
        require-doc:
          ignore-exported: false
          ignore-unexported: true
        start-with-name:
          include-unexported: true
    godot:
      scope: toplevel
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
    # The following settings should match revive.toml
    revive:
      severity: warning
      confidence: 0.8
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
        - name: atomic
        - name: banned-characters
        - name: bare-return
        - name: blank-imports
        - name: bool-literal-in-expr
        - name: call-to-gc
        - name: comment-spacings
        - name: comments-density
        - name: confusing-naming
          disabled: true
        - name: confusing-results
        - name: constant-logical-expr
        - name: context-as-argument
        - name: context-keys-type
        - name: cyclomatic
          disabled: true
        - name: datarace
        - name: deep-exit
        - name: defer
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: enforce-map-style
          arguments: ["literal"]
        - name: enforce-repeated-arg-type-style
        - name: enforce-slice-style
          arguments: ["literal"]
        - name: enforce-switch-style
          arguments: ["allow-no-default"]
        - name: epoch-naming
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: file-header
          disabled: true
        - name: file-length-limit
          disabled: true
        - name: filename-format
          # Override the default pattern to forbid .go files with uppercase letters and dashes.
          arguments: ["^[_a-z][_a-z0-9]*\\.go$"]
        - name: flag-parameter
          disabled: true
        - name: forbidden-call-in-wg-go
        - name: function-length
          disabled: true
        - name: function-result-limit
        - name: get-return
        - name: identical-branches
        - name: identical-ifelseif-branches
        - name: identical-ifelseif-conditions
        - name: identical-switch-branches
        - name: identical-switch-conditions
        - name: if-return
        - name: import-alias-naming
        - name: import-shadowing
        - name: imports-blocklist
          arguments: ["sort"]
        - name: increment-decrement
        - name: indent-error-flow
        - name: inefficient-map-lookup
        - name: line-length-limit
          arguments: [200]
        - name: max-control-nesting
        - name: max-public-structs
          arguments: [10]
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: nested-structs
        - name: optimize-operands-order
        - name: package-comments
        - name: package-directory-mismatch
        - name: range
        - name: range-val-address
        - name: range-val-in-closure
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: redundant-build-tag
        - name: redundant-import-alias
        - name: redundant-test-main-exit
        - name: string-format
        - name: string-of-int
        - name: struct-tag
          arguments: ["json,inline"]
        - name: superfluous-else
        - name: time-date
        - name: time-equal
        - name: time-naming
        - name: unchecked-type-assertion
          disabled: true
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unhandled-error
          disabled: true
        - name: unnecessary-format
        - name: unnecessary-if
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unsecure-url-scheme
        - name: unused-parameter
        - name: unused-receiver
        - name: use-any
        - name: use-errors-new
        - name: use-fmt-print
        - name: use-slices-sort
        - name: use-waitgroup-go
        - name: useless-break
        - name: useless-fallthrough
        - name: var-declaration
        - name: var-naming
        - name: waitgroup-by-value
    unparam:
      check-exported: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mgechev/revive)

issues:
  # Show all issues from a linter.
  max-issues-per-linter: 0
  # Show all issues with the same text.
  max-same-issues: 0
  # Show all issues for a line.
  uniq-by-line: false
