# This is the configuration for golangci-lint.
# See https://golangci-lint.run/usage/configuration/ for details.

version: "2"

linters:
  default: none
  enable:
    - dupword
    - embeddedstructfieldcheck
    - gocritic
    - godoclint
    - godot
    - gosec
    - govet
    - ineffassign
    - misspell
    - modernize
    - musttag
    - nolintlint
    - recvcheck
    - revive
    - sloglint
    - staticcheck
    - testpackage
    - thelper
    - thelper
    - unconvert
    - unparam
    - unused
    - wastedassign

  exclusions:
    warn-unused: true
    rules:
      - path: '(.+)_test\.go'
        linters:
          - godoclint
      - linters:
          - godoclint
        text: 'symbol should have a godoc \("Visit"\)'
      - linters:
          - testpackage
        text: 'package should be `rule_test` instead of `rule`'
      - linters:
          - testpackage
        text: 'package should be `lint_test` instead of `lint`'
      - linters:
          - testpackage
        text: 'package should be `cli_test` instead of `cli`'
      - linters:
          - testpackage
        text: 'package should be `formatter_test` instead of `formatter`'
      - linters:
          - gosec
        path: rule/epoch_naming.go
      - linters:
          - gosec
        path: rule/context_keys_type.go
      - linters:
          - gosec
        path: rule/errorf.go
      - linters:
          - gosec
        path: rule/modifies_value_receiver.go
      - linters:
          - gosec
        path: rule/range_val_address.go
      - linters:
          - gosec
        path: rule/string_of_int.go
      - linters:
          - gosec
        path: rule/time_naming.go
      - linters:
          - gosec
        path: rule/unexported_return.go
      - linters:
          - gosec
        path: rule/unhandled_error.go
      - linters:
          - gosec
        path: rule/var_declarations.go

  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - hugeParam
        - rangeValCopy
    godoclint:
      default: all
      options:
        max-len:
          length: 120
        require-doc:
          ignore-exported: false
          ignore-unexported: true
        start-with-name:
          include-unexported: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    misspell:
      locale: US
    nolintlint:
      allow-unused: true
      require-explanation: true
      require-specific: true
    # The following settings should match revive.toml
    revive:
      severity: warning
      confidence: 0.8
      rules:
        - name: bare-return
        - name: blank-imports
        - name: comment-spacings
        - name: constant-logical-expr
        - name: context-as-argument
        - name: context-keys-type
        - name: datarace
        - name: deep-exit
        - name: dot-imports
        - name: empty-block
        - name: empty-lines
        - name: enforce-map-style
          arguments: ["literal"]
        - name: enforce-slice-style
          arguments: ["literal"]
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: filename-format
          # Override the default pattern to forbid .go files with uppercase letters and dashes.
          arguments: ["^[_a-z][_a-z0-9]*\\.go$"]
        - name: identical-branches
        - name: increment-decrement
        - name: indent-error-flow
        - name: line-length-limit
          arguments: [200]
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: redundant-build-tag
        - name: superfluous-else
        - name: time-date
        - name: time-equal
        - name: time-naming
        - name: unexported-naming
        - name: unexported-return
        - name: unnecessary-format
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: unused-receiver
        - name: useless-break
        - name: use-any
        - name: use-fmt-print
        - name: var-declaration
        - name: var-naming

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mgechev/revive)

issues:
  # Show all issues from a linter.
  max-issues-per-linter: 0
  # Show all issues with the same text.
  max-same-issues: 0
  # Show all issues for a line.
  uniq-by-line: false
