# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
---
archives:
  -
    replacements:
      386: i386
      amd64: x86_64
      darwin: Darwin
      linux: Linux
      windows: Windows
before:
  hooks:
    - "go mod download"
    - "go generate ./..."
builds:
  -
    env:
      - CGO_ENABLED=0
      - BUILDER=GoReleaser
    goos:
      - linux
      - darwin
      - windows

dockers:
- image_templates: ["ghcr.io/mgechev/revive:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mgechev/revive
  - --label=org.opencontainers.image.source=https://github.com/mgechev/revive
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
  
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  sort: asc
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
project_name: revive
