# GoReleaser configuration for revive.
# Documentation: https://goreleaser.com/
---
version: 2
archives:
  - id: revive
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
builds:
  -
    env:
      - CGO_ENABLED=0
      - BUILDER=GoReleaser
    goos:
      - linux
      - darwin
      - windows

changelog:
  filters:
    exclude:
      - "^test:"
  sort: asc
checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ .Tag }}-next"
project_name: revive
