# Contains the list of all untyped rules.

[rule.add-constant]
[rule.argument-limit]
[rule.atomic]
[rule.banned-characters]
[rule.bare-return]
[rule.blank-imports]
[rule.bool-literal-in-expr]
[rule.call-to-gc]
[rule.cognitive-complexity]
[rule.comment-spacings]
[rule.comments-density]
[rule.confusing-naming]
[rule.confusing-results]
[rule.constant-logical-expr]
[rule.context-as-argument]
[rule.cyclomatic]
[rule.datarace]
[rule.deep-exit]
[rule.defer]
[rule.dot-imports]
[rule.duplicated-imports]
[rule.early-return]
[rule.empty-lines]
[rule.enforce-map-style]
[rule.enforce-repeated-arg-type-style]
[rule.enforce-slice-style]
[rule.enforce-switch-style]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.file-header]
[rule.file-length-limit]
[rule.filename-format]
[rule.flag-parameter]
[rule.forbidden-call-in-wg-go]
[rule.function-length]
[rule.function-result-limit]
[rule.get-return]
[rule.identical-branches]
[rule.identical-ifelseif-branches]
[rule.identical-ifelseif-conditions]
[rule.identical-switch-branches]
[rule.identical-switch-conditions]
[rule.if-return]
[rule.import-alias-naming]
[rule.import-shadowing]
[rule.imports-blocklist]
[rule.increment-decrement]
[rule.var-naming]
[rule.package-comments]
[rule.package-naming]
[rule.package-directory-mismatch]
[rule.range]
[rule.receiver-naming]
[rule.indent-error-flow]
[rule.line-length-limit]
    arguments = [200]
[rule.max-control-nesting]
[rule.max-public-structs]
[rule.modifies-parameter]
[rule.nested-structs]
[rule.optimize-operands-order]
[rule.range-val-in-closure]
[rule.redefines-builtin-id]
[rule.redundant-build-tag]
[rule.redundant-import-alias]
[rule.redundant-test-main-exit]
[rule.string-format]
[rule.struct-tag]
[rule.superfluous-else]
[rule.unconditional-recursion]
[rule.unexported-naming]
[rule.unnecessary-if]
[rule.unnecessary-format]
[rule.unnecessary-stmt]
[rule.unreachable-code]
[rule.unsecure-url-scheme]
[rule.unused-parameter]
[rule.unused-receiver]
[rule.use-any]
[rule.use-errors-new]
[rule.use-fmt-print]
[rule.use-slices-sort]
[rule.use-waitgroup-go]
[rule.useless-break]
[rule.useless-fallthrough]
[rule.waitgroup-by-value]
