package lint_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/mgechev/revive/lint"
)

// goVersionRule reports the Go version detected for the package of every linted file.
type goVersionRule struct{}

func (*goVersionRule) Name() string { return "go-version" }

func (*goVersionRule) Apply(file *lint.File, _ lint.Arguments) []lint.Failure {
	return []lint.Failure{{Confidence: 1, Failure: file.Pkg.GoVersion().String()}}
}

func TestLint_goVersionFromModFile(t *testing.T) {
	goVersion := func(t *testing.T, filename string) string {
		t.Helper()

		got := lintFile(t, filename, "package foo\n", []lint.Rule{&goVersionRule{}}, lint.Config{}, nil)
		if len(got) != 1 {
			t.Fatalf("expected exactly 1 failure, got %d: %+v", len(got), got)
		}
		return got[0].Failure
	}

	t.Run("go.mod file exists in a parent directory", func(t *testing.T) {
		rootDir := t.TempDir()
		err := os.WriteFile(filepath.Join(rootDir, "go.mod"), []byte("module example.com/test\n\ngo 1.21\n"), 0o600)
		if err != nil {
			t.Fatal(err)
		}
		nestedDir := filepath.Join(rootDir, "nested", "dir", "structure")
		if err := os.MkdirAll(nestedDir, 0o750); err != nil {
			t.Fatal(err)
		}

		if got, want := goVersion(t, filepath.Join(nestedDir, "foo.go")), "1.21.0"; got != want {
			t.Errorf("detected Go version %q, want %q", got, want)
		}
	})

	t.Run("go.mod file does not exist", func(t *testing.T) {
		if got, want := goVersion(t, filepath.Join(t.TempDir(), "foo.go")), "1.0.0"; got != want {
			t.Errorf("detected Go version %q, want %q", got, want)
		}
	})
}

func TestLint_skipsGeneratedFiles(t *testing.T) {
	tests := []struct {
		source    string
		generated bool
	}{
		{"// Code Generated by some tool. DO NOT EDIT.", false},
		{"// Code generated by some tool. DO NOT EDIT.", true},
		{"// Code generated by some tool. DO NOT EDIT", false},
		{"// Code generated  DO NOT EDIT.", true},
		{"// Code generated DO NOT EDIT.", false},
		{"\t\t// Code generated by some tool. DO NOT EDIT.\npackage foo\n", false},
		{"// Code generated by some tool. DO NOT EDIT.\npackage foo\n", true},
		{"package foo\n// Code generated by some tool. DO NOT EDIT.\ntype foo int\n", true},
		{"package foo\n // Code generated by some tool. DO NOT EDIT.\ntype foo int\n", false},
		{"package foo\n// Code generated by some tool. DO NOT EDIT. \ntype foo int\n", false},
		{"package foo\ntype foo int\n// Code generated by some tool. DO NOT EDIT.\n", true},
		{"package foo\ntype foo int\n// Code generated by some tool. DO NOT EDIT.", true},
	}

	// A file that is not skipped always produces a failure:
	// either the fake rule reports one, or the file is not valid Go and revive reports it as invalid.
	rules := []lint.Rule{&fakeRule{name: "rule1", failures: []lint.Failure{{Confidence: 1, Failure: "failure"}}}}

	for _, tt := range tests {
		t.Run(tt.source, func(t *testing.T) {
			got := lintFile(t, "test.go", tt.source, rules, lint.Config{}, nil)
			if skipped := len(got) == 0; skipped != tt.generated {
				t.Errorf("file skipped = %v, want %v (failures: %+v)", skipped, tt.generated, got)
			}
		})
	}

	t.Run("generated files are linted with IgnoreGeneratedHeader", func(t *testing.T) {
		got := lintFile(t, "test.go", "// Code generated by some tool. DO NOT EDIT.\npackage foo\n", rules, lint.Config{IgnoreGeneratedHeader: true}, nil)
		if len(got) != 1 {
			t.Errorf("expected exactly 1 failure, got %d: %+v", len(got), got)
		}
	})
}
